# Generated by Django 5.0.6 on 2024-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('ISBN', models.CharField(max_length=100, unique=True)),
                ('pages', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(upload_to='covers/')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
    ]
