# Generated by Django 5.0.6 on 2024-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
