# Generated by Django 5.0.6 on 2024-05-29 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_to_return_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 29, 1, 49, 26, 667148)),
        ),
    ]
